services:
  dart-db:
    image: postgres:18.1
    container_name: dart-db
    restart: unless-stopped
    env_file:
      - ./.env.local
    ports:
      - "5432:5432"
    volumes:
      - dart-db-data:/var/lib/postgresql

volumes:
  dart-db-data: